# Automation: Physical button triggers Leave Home scene
# Paste into automations.yaml on HA instance
# Reload: http://homeassistant.local:8123/developer-tools/yaml (Automations)
# Discover device_id by pressing the button and checking http://homeassistant.local:8123/logbook
# and creating an automation at http://homeassistant.local:8123/config/automation/edit/new (gives device_id and syntax)
# Device page: http://homeassistant.local:8123/config/devices/device/4390745362032b639a615b61b86d9eaa


- id: leave_home_button
  alias: Leave Home Button
  description: ""
  mode: single
  # Dimmer switch global (device_id: 4390745362032b639a615b61b86d9eaa)
  triggers:
    - device_id: 4390745362032b639a615b61b86d9eaa
      domain: hue
      type: initial_press # here AI did not generate correct synthax which is: intial press (no need to mention elsewhere)
      subtype: 4
      trigger: device
  conditions: []
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.leave_home_ha

