# Automation: Physical button triggers Play Random Music script
# Paste into automations.yaml on HA instance
# Reload: http://homeassistant.local:8123/developer-tools/yaml (Automations)
# Discover device_id by pressing the button and checking http://homeassistant.local:8123/logbook
# and doing an automation http://homeassistant.local:8123/config/automation/edit/new



- id: play_random_music_button
  alias: Play Random Music Button
  description: ""
  mode: single
  # Dimmer switch global (device_id: 4390745362032b639a615b61b86d9eaa)
  triggers:
    - entity_id: event.hue_dimmer_switch_global_button_1
      trigger: state
      attribute: event_type
      to: short_press
  conditions: []
  action:
    - action: script.turn_on
      target:
        entity_id: script.play_random_music

