# Automation: Physical button triggers Stop Music script
# Paste into automations.yaml on HA instance
# Reload: http://homeassistant.local:8123/developer-tools/yaml (Automations)
# Discover device_id by pressing the button and checking http://homeassistant.local:8123/logbook
# and doing an automation http://homeassistant.local:8123/config/automation/edit/new


- id: stop_music_button
  alias: Stop Music Button
  description: ""
  mode: single
  triggers:
    - device_id: 4390745362032b639a615b61b86d9eaa  # Dimmer switch entrance
      domain: hue
      type: short_press
      subtype: 2
      trigger: device
  conditions: []
  action:
    - action: script.turn_on
      target:
        entity_id: script.stop_music


- id: cut_music_plug_button
  alias: Cut Music Plug Button
  description: ""
  mode: single
  triggers:
    - device_id: 4390745362032b639a615b61b86d9eaa  # Dimmer switch entrance
      domain: hue
      type: short_press
      subtype: 3
      trigger: device
  conditions: []
  action:
    - action: script.turn_on
      target:
        entity_id: script.cut_music_plug
